### ISSUE TITLE
irk-numeric-question-step doesn't show number keypad on iOS

### ISSUE THREAD

**Issue by justinberry** [ninoguba/ionic-researchKit#13]
Hi there,

I found on my iOS 9.1 simulator (I don't have access to a wide range of devices, so I'm unsure exactly which versions are showing this) when clicking the irk-numeric-question-step field it shows the normal keyboard. I was able to get the number keypad to show up by modifying the directive via adding pattern="[0-9]*" to the input tag.

Edit: alternatively setting type="tel" on the input tag fixes the issue and allows for enforcing a maxlength (again, unsure of compatibilities with older devices).

Hope this helps.

**Comment by ninoguba** [comment]
On iOS, the default keyboard that shows up when input type='number' is the UIKeyboardType.NumbersAndPunctuation which is appropriate for general numerical use cases.  The only problem with this is it doesn't prevent you from entering inappropriate characters.  For that I had to just rely on the validation that the value entered is a valid numerical value and falls within the min/max if set.

Your proposed workarounds may work only if the values you expect are strictly digits only (no decimals, commas, negatives, etc).

On the Android side, the current implementation just works - it shows a numeric keypad that also allows only a dot, dash, and comma characters to be entered.  

Take note that this is different from the keypad that shows when input type='tel' as that is suited for phone number entry.
