### ISSUE TITLE
Issue with scaled step task on mobile devices

### ISSUE THREAD

**Issue by ajerrison-manchester** [ninoguba/ionic-researchKit#14]
Hi, 
I'm very new to both Ionic and Angular, so may be making a schoolboy error, but when I try to run the ResearchKit starter app on either my Android phone or iPad I find that the range widgets within irkScaleQuestionStep do not appear to work (they are OK in a web browser). 

I think that this might be a similar problem to the case highlighted in the below link, i.e. the slidebox's events seem to override the range's events. On Android I can tap the range input and the button will move to the point I've tapped, however I can't drag it (the slidebox drags instead). On iOS I can't tap or drag - drag moves the slidebox. 

I've tried to implement the fix suggested below, but only succeeded in preventing the slidebox from moving when dragging on the range widget. However the range widget itself still does not move. As you are obviously more experienced with both platforms do you have any ideas? I am using Ionic 1.2.4 and Angular 1.4.3.

https://forum.ionicframework.com/t/range-slider-in-slide-box-slide-how-to-prevent-event-bubbling/4075

Thanks, Andrew

**Comment by ninoguba** [comment]
This could be due to changes in Ionic 1.2.  I'll take a look.

Thanks,
Nino

**Comment by ajerrison-manchester** [comment]
Hi Nino, 

Does the underlying container need to be a slidebox? For my purposes at least a sliding mechanism is not necessary and I was considering trying to rewrite with just standard views. It would be a lot of work though - much easier to get this working if it is possible!

Thanks, Andrew

**Comment by ninoguba** [comment]
Andrew,

Got the chance to look into this and definitely this issue is only evident when using Ionic 1.2.4.  When I built this I was still using Ionic 1.1.0 and haven't gotten the chance to upgrade the framework with the latest Ionic version (which they just officially released a few weeks ago).

The slidebox was the most suitable container for this because it can support any number of slides (or "steps") in a single view.  I agree implementing this just with standard views will make it more complicated.

I'll try to see how this issue can be fixed with 1.2.4 but for the meantime, if you're pressed for time, will downgrading to Ionic 1.1.0 work for you, at least until we get this issue resolved?

Thanks,
Nino

**Comment by ajerrison-manchester** [comment]
Thanks Nino, 

Yes I've downgraded to Ionic 1.1.1 and it seems to have solved the range issue. The rest of my app (so far) is unaffected too. So that is OK for me.

The main reason I was using 1.2.4 was because I've literally only just found Ionic, and obviously the latest version is the default. I actually found this plugin first, and thought I'd try Ionic so that I could use your library! Pretty typical for me to find a bug with Ionic with almost the first thing I try. :-) 

Andrew

**Comment by Matt2012** [comment]
Should this issue still be open?

**Comment by ninoguba** [comment]
This is due to changes in Ionic 1.2.4 which I opened a separate issue
tracker to fully support it.  At this time this plugin works fully with the
v1.1.0 only.

On Tuesday, March 8, 2016, Matt Bourne notifications@github.com wrote:

> Should this issue still be open?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ninoguba/ionic-researchKit/issues/14#issuecomment-194042143
> .

## 

Sent from Gmail Mobile

**Comment by Matt2012** [comment]
Do you have plans to support recent versions of ionic?

I am happy to try and submit a pull request for the issue - but it would be great to know if you are actively maintaining this project going forward?

Also did you ever get around to investigating the issue in greater depth - would the step views need rearcitecting away from slidebox or do we just need to override some behaviour?

I imagine ranges in slide boxes effects not just this project?

**Comment by ninoguba** [comment]
In Ionic 1.2 they changed the way they implemented Slide Box based on the
Swiper widget (http://blog.ionic.io/announcing-ionic-1-2/).  This plugin
extended the old implementation of the Slide Box component to make the
survey steps UI possible.   To support versions >=1.2 this plugin has to be
based on the Swiper widget as well to make it compatible.  I'm currently
working to support this.
