### ISSUE TITLE
Update to Ionic 1.2.4 (now 1.3)

### ISSUE THREAD

**Issue by ninoguba** [ninoguba/ionic-researchKit#15]
I just updated to Ionic 1.2.4 and have so far only seen the following compatibility issue(s):
- Scaled Question Step sliders don't slide on actual mobile devices as expected (thanks to Andrew for reporting)

According to Ionic's blog post on the release of version 1.2, they've made significant changes to the following components that require more analysis to fully support them with Ionic-ResearchKit.
- ion-slides
- ion-input
- ion-label

Please stay tuned for updates.

Thanks,
Nino

**Comment by HansLui** [comment]
So..this version of the ionicResearchKit is not compatible with the current version of Ionic?

**Comment by ninoguba** [comment]
Not yet...  The most critical component that needs to be updated is the ion-slide that this plugin extended to implement the irk-steps.

**Comment by ninoguba** [comment]
Ionic has announced the availability of version 1.3.  Just by looking at the changelog, the following changes may an effect on this framework
- slides
- modal

If anyone has tried upgrading to 1.3 and found issues, I would appreciate if you can report them here.

Thanks,
Nino

**Comment by Matt2012** [comment]
Is there still no update on this bug? The broken sliders is a real shame. Are you able to share what you've tried - before I have go myself?

Have you tried using the deprecated ion-slides within 1.24?

**Comment by ninoguba** [comment]
This is a major change since in Ionic 1.2 the sliders are now using on the
Swiper widget and it has its own separate APIs.

What I havent tried is figure out how to make the old ionic.views.Slider
available and run alongside the newer version of the Slider.  Look
at changing line 237 of ionic-researchkit.js

If you can help with this that would be awesome as I'm a bit swamped with
work at the moment.

Thanks!

On Tuesday, May 3, 2016, Matt Bourne notifications@github.com wrote:

> Is there still no update on this bug? The broken sliders is a real shame.
> Are you able to share what you've tried - before I have go myself?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ninoguba/ionic-researchKit/issues/15#issuecomment-216687858

## 

Sent from Gmail Mobile

**Comment by Matt2012** [comment]
@ninoguba Can you not use 

```
<ion-slide-box on-slide-changed="slideHasChanged($index)">
  <ion-slide>
    <div class="box blue"><h1>BLUE</h1></div>
  </ion-slide>
  <ion-slide>
    <div class="box yellow"><h1>YELLOW</h1></div>
  </ion-slide>
  <ion-slide>
    <div class="box pink"><h1>PINK</h1></div>
  </ion-slide>
</ion-slide-box>
```

http://ionicframework.com/docs/api/directive/ionSlideBox/

As opposed to 

http://ionicframework.com/docs/api/directive/ionSlides/

I'm actually not clear where the ion slides are being drawn.

**Comment by ninoguba** [comment]
That is exactly the issue.  Ionic has deprecated the ionSlideBox, which if you look at the source code, is instantiating the ionic.views.Slider.  It's the same ionic.views.Slider that I'm instantiating to make the ionicRK steps UI.

On the newer versions of Ionic however, the underlying implementation of the ionic.views.Slider was significantly different as it is now using the Swiper widget under its hood and thus breaks ionicRK's core.

What I'm suggesting you try is copy the old implementation of ionic.views.Slider from the 1.1 version, paste it on its own js file, reference it in your index.html file, rename it to something like ionic.views.LegacySlider, update ionicRK's line 237 to instantiate this LegacySlider, and see how it works.

**Comment by Matt2012** [comment]
Ok great - will have a look at that and report back.

**Comment by ninoguba** [comment]
Ok I finally had some availability to look into this further and will be posting updates on my progress to fully support the latest non-beta version of Ionic (currently 1.3.1).

From initial tests, the following issues need to be fixed:
- IRKScaleQuestionStep doesn't allow sliding
- ~~IRKImageChoiceQuestionStep doesn't show icons (but images work)~~
- ~~IRKTwoFingerTappingIntervalTask errors with a reference to $parseInt~~

**Comment by ninoguba** [comment]
The issue with the range sliders is it doesn't work when placed inside an ion-slide-box or the new ion-slides component.  This is an inherent issue with Ionic 1.3.x from what I gather so far...

**Comment by ninoguba** [comment]
Ok I opened an issue tracker with Ionic.  The issue turns out to be with range sliders inside modal views.  

You can track the issue here:
https://github.com/driftyco/ionic/issues/6885

**Comment by PuckCh** [comment]
Hello,

I confirm that ionic 1.3 break the scrolling with Ionic Research Kit.
I have looked at the issue on the Ionic and the temporarily fix proposed by basdp corrects the problem.

In the mean time that Ionic will correct the scrolling problem, you can change all the `class="irk-slider"` with `class="scroll irk-slider"`. It works for me with the stock 1.3.1 version of Ionic.

HTH, and have a nice day.

-- Olivier

**Comment by ninoguba** [comment]
@PuckCh Thanks!  I've now updated the library with your suggestion and tested it with Ionic 1.3.1 and everything works now as expected.

@Matt2012 @HanZen13 FYI
