### ISSUE TITLE
ng-repeat with dynamic ID causing multiple errors

### ISSUE THREAD

**Issue by nicksteffens** [ninoguba/ionic-researchKit#17]
Trying to dynamically pull in ID's off a JSON play load. This is breaking in the directives as it will crashes when the compile encounters another pair of `{{`.
### Template

```
<irk-task ng-repeat="q in questions track by $index">
        <irk-scale-question-step id="{{q.id}}"
          title="{{q.question}}"
          text="1 being Never &amp; 5 Almost Always"
            min="1" max="5" step="1" value="3" />
</irk-task>
```

I found encounter this code issue here: https://github.com/ninoguba/ionic-researchKit/blob/master/www/lib/ionic-researchkit/ionic-researchkit.js#L670
## Error:

```
ionic.bundle.js:25642 Error: [$parse:syntax] Syntax Error: Token '{' is not a valid identifier at column 18 of the expression [$parent.formData.{{q.id] starting at [{{q.id].
http://errors.angularjs.org/1.4.3/$parse/syntax?p0=%7B&p1=is%20not%20a%20valid%20identifier&p2=18&p3=%24parent.formData.%7B%7Bq.id&p4=%7B%7Bq.id
    at ionic.bundle.js:13380
    at Object.throwError (ionic.bundle.js:26193)
    at Object.identifier (ionic.bundle.js:26140)
    at Object.primary (ionic.bundle.js:26108)
    at Object.unary (ionic.bundle.js:26076)
    at Object.multiplicative (ionic.bundle.js:26063)
    at Object.additive (ionic.bundle.js:26054)
    at Object.relational (ionic.bundle.js:26045)
    at Object.equality (ionic.bundle.js:26036)
    at Object.logicalAND (ionic.bundle.js:26028)
```

**Comment by ajerrison-manchester** [comment]
Not a direct answer for your problem, but as a workaround you could try using $ionicModal.fromTemplate() instead of $ionicModal.fromTemplateURL() when creating your modal view. You obviously have to build up the whole markup dynamically rather than just using an ng-repeat (which is a pain I know) but it should work. 

I used this way myself because my surveys tend to have many different question types in random orders, and my angular is pretty rudimentary at present so I couldn't figure out an 'in view' method of doing it. Looks like I might have had problems even if I had worked it out though!

Hope that helps, or at least doesn't hinder.

**Comment by nicksteffens** [comment]
@ajerrison-manchester I'll give that try. Thanks for the quick response.

**Comment by ninoguba** [comment]
@ajerrison-manchester thanks for that workaround.  

So I looked into the issue and researched ways to resolve it but so far haven't arrived at a workable solution to support dynamic attributes. Looks like this won't be a simple fix.  Anyone is welcome to take a stab at finding a solution. =)

**Comment by nicksteffens** [comment]
@ajerrison-manchester so now that i did `fromTemplate` rendering is happening fine i am unable to find where the `$scope.data` is being stored. It appears that i do not have access to the `irkresults` service. 

PS. my apologies very new to angular.

**Comment by nicksteffens** [comment]
## Update: 

So when needing to use dynamic data, one would have to do the solution of using `fromTemplate` loop over they data to create the template then passing it to `$ionicModal` as a template string.

[Solution Gist](https://gist.github.com/nicksteffens/56a86a679e4b062341cb79a05105f110)
