### ISSUE TITLE
voice task audio recording on android

### ISSUE THREAD

**Issue by satra** [ninoguba/ionic-researchKit#33]
@ninoguba - on my android phone, the first time the voice recording is requested, it asks for permission. after setting the permission, it seems that the recording doesn't playback.

launch app, do a voice recording for the first time, will ask for permission, give permission, and then record, try to play back recording.

**Comment by ninoguba** [comment]
thanks I'll investigate...

**Comment by ninoguba** [comment]
@satra looks like this is related to Android M's new way of handling app permissions. My phone is stuck on Android L so I cant reproduce your issue.

**Comment by ninoguba** [comment]
@satra I suggest to make sure you have the latest version of cordova and then remove-add the media plugin like so:

cordova plugin rm cordova-plugin-media
cordova plugin add cordova-plugin-media

The rebuild the app and retest on your phone to see if the issue has been resolved.

**Comment by satra** [comment]
@ninoguba - i can try again but the way i have been building it is as follows:

`ionic state reset` (which removes and installs platforms and plugins)

and then build the app. i'll post back after i try again. i can also check that cordova is the latest version (i'm pretty sure it is).

**Comment by satra** [comment]
@ninoguba - for some reason none of the recordings are actually saved on disk anymore - they all say 0 bytes. trying to investigate this now.

**Comment by satra** [comment]
this is an issue with versions of the cordova-plugin-media > 2.3.0

**Comment by ninoguba** [comment]
Thanks @satra!
