### ISSUE TITLE
Hi, We are currently facing screen flickering issue in case of higher number of slides(173 steps). Is there a problem which we can look at ?

### ISSUE THREAD

**Issue by m1012290** [ninoguba/ionic-researchKit#37]

**Comment by ninoguba** [comment]
Hi. The framework is mostly based on the Ionic Slidebox and need to be optimized to dynamically lazy load steps to maybe address the issue you experience.  Please refer to the following as they might help you.

https://github.com/driftyco/ionic/issues/1678

**Comment by m1012290** [comment]
Thank you for your timely reply on this.

**Comment by m1012290** [comment]
I was able to pull off dynamic slider. Thank you for the pointer.
